src/main/java/se/sundsvall/invoicesender/Application.java, src/main/java/se/sundsvall/invoicesender/integration/db/DbIntegration.java, src/main/java/se/sundsvall/invoicesender/integration/db/FileRepository.java, src/main/java/se/sundsvall/invoicesender/integration/db/entity/BatchEntity.java, src/main/java/se/sundsvall/invoicesender/integration/db/entity/FileEntity.java, src/main/java/se/sundsvall/invoicesender/integration/db/entity/ItemEntity.java, src/main/java/se/sundsvall/invoicesender/integration/raindance/RaindanceIntegration.java, src/main/java/se/sundsvall/invoicesender/model/Batch.java, src/test/java/se/sundsvall/invoicesender/integration/db/DbIntegrationTests.java, src/test/java/se/sundsvall/invoicesender/integration/db/entity/BatchEntityTests.java, src/test/java/se/sundsvall/invoicesender/integration/db/entity/FileEntityTests.java, src/test/java/se/sundsvall/invoicesender/integration/db/entity/ItemEntityTests.java, src/test/java/se/sundsvall/invoicesender/model/BatchTests.java
Implements a simple database backup of fetched batches as a safety measure, since original batch files are overwritten after processing.
=> UF-5743 - Backups

src/main/java/se/sundsvall/invoicesender/integration/raindance/RaindanceIntegration.java
Changes the Raindance batch processing so that each batch (file) gets its own work directory instead of using a common one.
=> UF-XYZ - Batch work directories

pom.xml
Increases JVM limits, to hopefully be able to handle massive invoice batches with thousands of invoices.
=> UF-XYZ - Increase JVM limits

pom.xml, src/main/java/se/sundsvall/invoicesender/service/InvoiceProcessor.java, src/main/java/se/sundsvall/invoicesender/service/ScheduledRestart.java, src/main/java/se/sundsvall/invoicesender/service/util/CronUtil.java, src/test/java/se/sundsvall/invoicesender/service/InvoiceProcessorTests.java
Adds the possibility of scheduling restarts, maybe to be able to remedy file locks that appear randomly
=> UF-XYZ - Scheduled restarts

pom.xml, src/main/java/se/sundsvall/invoicesender/integration/messaging/MessagingIntegration.java, src/main/java/se/sundsvall/invoicesender/integration/party/PartyIntegration.java, src/main/java/se/sundsvall/invoicesender/model/Item.java, src/main/java/se/sundsvall/invoicesender/service/InvoiceProcessor.java, src/main/resources/integrations/messaging-api-4.2.yml
Adds special handling for "autogiro" invoices, in the sense that they shouldn't be payable, since payment is already set up
=> UF-7340 - Handle "autogiro" invoices

src/integration-test/resources/application-it.yml, src/main/java/se/sundsvall/invoicesender/integration/raindance/RaindanceIntegration.java, src/main/java/se/sundsvall/invoicesender/integration/raindance/RaindanceIntegrationProperties.java, src/main/java/se/sundsvall/invoicesender/model/Batch.java, src/main/java/se/sundsvall/invoicesender/service/InvoiceProcessor.java, src/test/java/se/sundsvall/invoicesender/model/BatchTests.java, src/test/java/se/sundsvall/invoicesender/service/InvoiceProcessorTests.java, src/test/resources/application-junit.yml
Adds some additional invoice handling and archiving
=> UF-7342/7338 - Additional invoice handling

src/main/java/se/sundsvall/invoicesender/service/InvoiceProcessor.java
Changes logging so that the actual result of an invoice being sent is logged properly.
=> Adds proper logging for invoice sending status

.gitignore, src/main/java/se/sundsvall/invoicesender/service/InvoiceProcessor.java, src/main/java/se/sundsvall/invoicesender/service/InvoiceProcessorProperties.java, src/main/java/se/sundsvall/invoicesender/service/ScheduledRestart.java, src/main/resources/application.yml, src/main/resources/db/migration/V1.5__migrate_item_status_from_enum.sql, src/test/java/se/sundsvall/invoicesender/service/InvoiceProcessorTests.java, src/test/java/se/sundsvall/invoicesender/service/ScheduledRestartTests.java, src/test/resources/application-junit.yml
Changes the (item) status db column from an enum to a varchar column. Also, moves from using a number of single @Value-injected properties to a common @ConfigurationProperties configuration.
=> UF-10187 - Change the status db column

src/main/java/se/sundsvall/invoicesender/integration/raindance/RaindanceIntegration.java
=> Reverted an unintended change

src/integration-test/java/apptest/InvoiceSenderIT.java, src/integration-test/resources/docker-compose.yml, src/main/java/se/sundsvall/invoicesender/integration/raindance/RaindanceIntegration.java
=> Updated file handling in integration tests

src/integration-test/java/apptest/InvoiceSenderIT.java, src/integration-test/resources/docker-compose.yml, src/main/java/se/sundsvall/invoicesender/integration/raindance/RaindanceIntegration.java
=> Uf 10984 changes

src/main/java/se/sundsvall/invoicesender/integration/citizen/CitizenClient.java, src/main/java/se/sundsvall/invoicesender/integration/db/BatchRepository.java, src/main/java/se/sundsvall/invoicesender/integration/db/ItemRepository.java, src/main/java/se/sundsvall/invoicesender/integration/messaging/MessagingClient.java, src/main/java/se/sundsvall/invoicesender/integration/party/PartyClient.java
=> UF-11348: Add Circuitbreakers

src/integration-test/java/apptest/InvoiceSenderIT.java
=> Added writing permissions for local directories

src/main/java/se/sundsvall/invoicesender/integration/raindance/RaindanceIntegration.java
=> Fixed url to samba share

src/main/resources/application.yml
=> Added circuitbreaker configuration

src/main/resources/integrations/messaging-api.yml
=> UF-14629: Update to messaging 6.1

src/integration-test/resources/InvoiceSenderIT/__files/test2_processInvoices/mappings/api-citizen-get-person.json, src/integration-test/resources/InvoiceSenderIT/__files/test3_processInvoices/mappings/api-citizen-get-person.json, src/main/java/se/sundsvall/invoicesender/integration/citizen/CitizenClient.java, src/main/java/se/sundsvall/invoicesender/integration/citizen/CitizenIntegration.java, src/main/java/se/sundsvall/invoicesender/service/InvoiceProcessor.java, src/test/java/se/sundsvall/invoicesender/integration/citizen/CitizenIntegrationTests.java, src/test/java/se/sundsvall/invoicesender/service/InvoiceProcessorTests.java
=> UF-14661: Updated citizen integration to v3

src/main/java/se/sundsvall/invoicesender/api/BatchResources.java, src/main/java/se/sundsvall/invoicesender/integration/citizen/CitizenIntegration.java, src/main/java/se/sundsvall/invoicesender/integration/messaging/MessagingMapper.java, src/main/java/se/sundsvall/invoicesender/integration/party/PartyIntegration.java, src/main/java/se/sundsvall/invoicesender/service/InvoiceProcessor.java, src/main/java/se/sundsvall/invoicesender/util/LegalIdUtil.java, src/test/java/se/sundsvall/invoicesender/api/BatchResourceTests.java, src/test/java/se/sundsvall/invoicesender/integration/party/PartyIntegrationTests.java, src/test/java/se/sundsvall/invoicesender/util/LegalIdUtilTests.java
* Updated call to party, sets the legalId based on a calculated guess instead of testing both 20th and 21st century.
=> UF-15746 Refactored Party call

pom.xml
* Reverted jsoup version to 1.19.1
=> UF-XYZ fix 

pom.xml, src/integration-test/java/apptest/InvoiceSenderIT.java, src/main/java/se/sundsvall/invoicesender/integration/db/DbIntegration.java, src/main/java/se/sundsvall/invoicesender/integration/raindance/RaindanceIntegration.java, src/main/java/se/sundsvall/invoicesender/service/InvoiceProcessor.java, src/main/java/se/sundsvall/invoicesender/service/util/XmlUtil.java, src/test/java/se/sundsvall/invoicesender/TestDataFactory.java, src/test/java/se/sundsvall/invoicesender/service/InvoiceProcessorTests.java, src/test/java/se/sundsvall/invoicesender/service/util/XmlUtilTests.java, src/test/resources/files/ArchiveIndex_singleFileForSearch.xml
=> Uf 16134 replace jsoup
